Homework 2
================
Henry Stoddard
9/24/2020

## Problem 1

Importing Mr Trash Wheel dataset and tidying

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------ tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.1
    ## v tidyr   1.1.1     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts --------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
trash_df = read_excel("./data/Mr_Trash_Wheel.xlsx")
```

    ## New names:
    ## * `` -> ...16
    ## * `` -> ...17

``` r
trash_df = janitor::clean_names(trash_df) %>% select(-notes, -x16, -x17) %>% drop_na(dumpster) %>% mutate(sports_balls = round(sports_balls), sports_balls = as.integer(sports_balls))
```

Importing and tidying precipitation datasets

``` r
precip2018_df = read_excel("./data/Mr_Trash_Wheel.xlsx", sheet = "2018 Precipitation", skip = 1) %>% janitor::clean_names() %>% drop_na(month) %>% mutate(year = 2018) %>% relocate(year)

precip2017_df = read_excel("./data/Mr_Trash_Wheel.xlsx", sheet = "2017 Precipitation", skip = 1) %>% janitor::clean_names() %>% drop_na(month) %>% mutate(year = 2017) %>% relocate(year)
```

Now combining datasets

``` r
precip_df = bind_rows(precip2018_df, precip2017_df) %>% mutate(month = month.name[month])
```

``` r
sum(pull(precip2018_df, total)) %>% view()
balls_df = select(trash_df, sports_balls, year)
balls2017_df = subset(balls_df, year == 2017) %>%summarise_if(is.numeric, na.rm = TRUE, median) %>% view()
```

## Data Summary

These two datasets include info from the Mr. Trashwheel collector in
Baltimore, MD. This machine collects trash and then stores it in a
dumpster. Data includes info on year, month, trash collected, and the
amounts of some specific kinds of trash. There are a total of 344 rows
in our final dataset. Additional data sheets include precipitation data
by month and year, which have a total of 24 rows. In 2018, there was a
total of 70.33 inches of rain. In 2017, the median number of sports
balls in a dumpster was 8.

## Problem 2

Importing, cleaning, and transforming the NYC transit data

``` r
nyc_df = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% janitor::clean_names() %>% select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% mutate(entry = recode(entry, YES = TRUE, NO = FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
summary(nyc_df)
```

    ##      line           station_name       station_latitude station_longitude
    ##  Length:1868        Length:1868        Min.   :40.58    Min.   :-74.03   
    ##  Class :character   Class :character   1st Qu.:40.69    1st Qu.:-73.99   
    ##  Mode  :character   Mode  :character   Median :40.73    Median :-73.96   
    ##                                        Mean   :40.73    Mean   :-73.94   
    ##                                        3rd Qu.:40.77    3rd Qu.:-73.91   
    ##                                        Max.   :40.90    Max.   :-73.76   
    ##                                                                          
    ##     route1             route2             route3             route4         
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##     route5             route6             route7              route8     
    ##  Length:1868        Length:1868        Length:1868        Min.   :1.000  
    ##  Class :character   Class :character   Class :character   1st Qu.:1.000  
    ##  Mode  :character   Mode  :character   Mode  :character   Median :4.000  
    ##                                                           Mean   :2.979  
    ##                                                           3rd Qu.:5.000  
    ##                                                           Max.   :5.000  
    ##                                                           NA's   :1820   
    ##      route9         route10        route11       entry        
    ##  Min.   :2.000   Min.   :3      Min.   :7      Mode :logical  
    ##  1st Qu.:2.000   1st Qu.:3      1st Qu.:7      FALSE:115      
    ##  Median :2.000   Median :3      Median :7      TRUE :1753     
    ##  Mean   :2.536   Mean   :3      Mean   :7                     
    ##  3rd Qu.:2.000   3rd Qu.:3      3rd Qu.:7                     
    ##  Max.   :5.000   Max.   :3      Max.   :7                     
    ##  NA's   :1840    NA's   :1845   NA's   :1845                  
    ##    vending          entrance_type         ada         
    ##  Length:1868        Length:1868        Mode :logical  
    ##  Class :character   Class :character   FALSE:1400     
    ##  Mode  :character   Mode  :character   TRUE :468      
    ##                                                       
    ##                                                       
    ##                                                       
    ## 

### data summary

This dataset contains information on NYC subway entrances and exits,
including the location, line, latitude and longitude, ADA accessibility,
and other information. So far, names have been tidied, some variables
were dropped, and entry was recoded from yes/no to true/false. This
dataset has 1868 rows and 19 columns. The data are tidy.

### additional analyses

``` r
distinct(nyc_df, station_name)
```

    ## # A tibble: 356 x 1
    ##    station_name            
    ##    <chr>                   
    ##  1 25th St                 
    ##  2 36th St                 
    ##  3 45th St                 
    ##  4 53rd St                 
    ##  5 59th St                 
    ##  6 77th St                 
    ##  7 86th St                 
    ##  8 95th St                 
    ##  9 9th St                  
    ## 10 Atlantic Av-Barclays Ctr
    ## # ... with 346 more rows

``` r
summary(pull(nyc_df, ada))
```

    ##    Mode   FALSE    TRUE 
    ## logical    1400     468

``` r
nyc2_df = select(nyc_df, entry, vending) %>% subset(vending =="NO")
sum(pull(nyc2_df, entry))
```

    ## [1] 69

There are 356 distinct stations. 468 Stations are ADA compliant. Out of
the 183 stations without vending, 69 (37.704918%) allow entry.
