---
title: "Homework 2"
author: "Henry Stoddard"
date: "9/24/2020"
output: github_document
---
## Problem 1

Importing Mr Trash Wheel dataset and tidying 

```{r library, import, tidy}
library(tidyverse)
library(readxl)
trash_df = read_excel("./data/Mr_Trash_Wheel.xlsx")
trash_df = janitor::clean_names(trash_df) %>% select(-notes, -x16, -x17) %>% drop_na(dumpster) %>% mutate(sports_balls = round(sports_balls), sports_balls = as.integer(sports_balls))
```

Importing and tidying precipitation datasets
```{r precipitation}
precip2018_df = read_excel("./data/Mr_Trash_Wheel.xlsx", sheet = "2018 Precipitation", skip = 1) %>% janitor::clean_names() %>% drop_na(month) %>% mutate(year = 2018) %>% relocate(year)

precip2017_df = read_excel("./data/Mr_Trash_Wheel.xlsx", sheet = "2017 Precipitation", skip = 1) %>% janitor::clean_names() %>% drop_na(month) %>% mutate(year = 2017) %>% relocate(year)
```

Now combining datasets
```{r merge}
precip_df = bind_rows(precip2018_df, precip2017_df) %>% mutate(month = month.name[month])
```

